# Custom Colors
add_newline = false

[character]
#disabled = true
#style = "bold bg:#4a5260 fg:#ABB2BF"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = ""
use_symbol_for_status = true

[directory]
#disabled = true
style = "bold bg:#4a5260 fg:#ABB2BF"
format = "[$read_only ]($style)[$path ]($style)[ ](fg:#4a5260)"
read_only=" "
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
